### ISSUE TITLE
Brainstorm-grade: storing test waivers as test metadata

### ISSUE THREAD

**Issue by t184256** [psss/tmt#506]
I'm looking into several approaches of how trivial test errors could be automatically waived by examining the test output.

1) test execution *env-agnostic*, where a wrapper is executed instead of the test, executes the test, captures output, processes it against some waiving rules, signals whether the output is expected or not (human attention is needed or not) using a return code.
2) *env-integrated*, where the test execution environment itself is modified to consult the waiving rules and classify the result into a richer, finer-grained set of statuses (+expected_fail, +unexpected_pass, +...),
3) *post-processing*, where an external tool is invoked to do post-processing of the stored output, apply waiving rulers and tweak the results accordingly

All three approaches, while being wildly different implementation-wise, have the following in common:
1) **waiving rules have to be stored somewhere**, unless hardcoded into a custom wrapper, and
2) **waiving rules** would vary significantly between SuT versions, and **would be highly likely to be subject to relevancy**.

That makes me think that might be beneficial to **treat waiving rules as test metadata, store those in fmf and reuse `adjust`** mechanism to pick the applicable ones between different executions.

I'm currently running a feasibility study of sorts using env-integrated approach, storing waivers alongside the tests, but not as test metadata yet. The aim at this stage is to explore how simple could we go with the rules semantics while still having a useful tool. If the whole ordeal turns out fruitful, I'll look into standardizing the format and, possibly, generalizing it into an env-agnostic approach.

All in all, I'll be raising this discussion in a more vocal manner if and when we decide that we want to buy into automated results waiving. Meanwhile, this ticket is a just forewarning that there might be demand to store test waiving rules in test metadata, and, if that'd be the case, those would be heavily 'adjust'ed. This, and a discussion prompt.

cc @tomato42, @ep69

**Comment by thrix** [comment]
@t184256  could we also note here the use cases for using the waivers, which should also explain what is meant by ` trivial test errors` pls?

**Comment by milosmalik** [comment]
Timeline of our use-case:
1) bug XYZ is reported -> 2) automated test which covers bug XYZ is created -> 3) bug XYZ is fixed -> 4) bug XYZ is tested and verified 

Very often, the following situation happens: the automated test gets executed before step 3.
I would like to see some automatic waiver (which analyses the environment and the test results) and says that the failure is expected because the bug XYZ is not yet fixed (build with the fix does not exist yet) or the environment contains an older build.
Such an automatic waiver would greatly improve the experience from various CI environments, where the situation happens on a daily basis.
I guess that metadata necessary for the decision making are: bug XYZ number, version+release of the fix

**Comment by t184256** [comment]
@milosmalik, you've captured it well. Scenarios when it's worth executing the test, even though it fails, and then ensuring it fails in a consistent, well-known manner: bug not fixed yet, issue cause by a component outside your control, verifying that old trusty bugs don't go anywhere on old versions... =) Modifying the test itself to account for all of this quickly leads to spaghetti code, concealing the original flow. Analyzing the logs separates the analysis from the execution.

Though I'd prefer to limit the decision to component version, distro version, and other axis already present in `fmf.Context`. Accessing bugtrackers is too fragile for my tastes.

An example I have at hand: library tries to enables Intel CET support, but one of its dependencies doesn't.
The test fails, outputting the following lines among the others:
```
:: [ 16:21:42 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.kztIj4Cp' should contain 'IBT'
...
:: [ 16:21:42 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.LF1Di5Fy' should contain 'SHSTK'
...
:: [ 16:21:42 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.kztIj4Cp' should contain 'IBT'
...
:: [ 16:21:42 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.LF1Di5Fy' should contain 'SHSTK'
```
but it's not the libraries fault and there's nothing we can or should do.
The library is fine. The test is fine.
IMO, this is a good candidate for solidifying the failure and explaining why it's acceptable,
so that we don't spend our precious review time on it, with rules similar to these:

```
adjust:
    expect:
      - pattern: |
          :: [ 00:00:00 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.XXXXXXXX' should contain 'IBT'
        times: 2
      - pattern: |
          :: [ 00:00:00 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.XXXXXXXX' should contain 'SHSTK'
        times: 2
    when: distro ~< fedora-35
    because: Fedora <=35 doesn't have CET enabled yet
```

This way, the test execution system won't flag this test for our attention - we know about this situation - until something changes.
When something changes (extra failures crop up, these ones disappear or we start running it on Fedora 35...) - it's re-review time.

**Comment by thrix** [comment]
Yeah, got it, thanks for sharing your use cases. It is basically expectedness like functionality. I like that it would be placed directly with the test case.

**Comment by tomato42** [comment]
> ```
> adjust:
>     expect:
>       - pattern: |
>           :: [ 00:00:00 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.XXXXXXXX' should contain 'IBT'
>         times: 2
>       - pattern: |
>           :: [ 00:00:00 ] :: [   FAIL   ] :: File '/var/tmp/rlRun_LOG.XXXXXXXX' should contain 'SHSTK'
>         times: 2
>     when: distro ~< fedora-35
>     because: Fedora <=35 doesn't have CET enabled yet
> ```

I think that shell globbing (`?` for single character and `*` for multiple characters, with escapes from them using `\?` and `\*`) would be more user friendly than `X` and `0` (and I think regexes would be overkill and problematic from escaping PoV)

**Comment by psss** [comment]
Is this something we would still like to look into? Let's discuss on the hacking session.

**Comment by psss** [comment]
Suggestion from the hacking session: Implement this as an additional `report` plugin which would be able to override `results.yaml`. @t184256, are you still interested in this?

**Comment by psss** [comment]
Summary from the triage meeting:

* Implementation: Additional report plugin, when enabled, could run as the first phase of the report step, check `results.yaml` and adjust it as needed according to pattern hints, then other `report` plugins would follow and do their work
* Sounds like a generally useful feature, added to the backlog with low priority for now.

**Comment by comps** [comment]
Resurrecting this with a different angle - keeping waivers as true real `fmf` tree nodes. A report plugin could still use them, but a new phase inserted between `execute` and `report` might make more sense if this is to be used (work) on Testing Farm and everywhere else, regardless of the report plugin

(Everything below looks polished with headings because it was in a Google Doc and I exported + cleaned it.)

---

## Auto-waivers, not comments on results

Waive a known failure as it happens, don't let the test fully fail + deal with failure later, like in result aggregators (ReportPortal, Nitrate, etc.).

## New fmf metadata type: **`waiver`**

* Identified by the `waiver` YAML key (like test is by `test`).
* Matches on a fmf test name expression (using `re.search`, matching other fmf/tmt logic).
* Optionally on a subresult, a log "grep" regular expression, ...
* Enabled/disabled by fmf context, matching other fmf/tmt logic (tests).

In a dedicated `.fmf` file:

```yaml
waiver: /dnf/Sanity/dnf-plugin-spacewalk-sanity
subresult: Install-a-pkg-with-GPG-verification
grep: 'Connecting to file.brq.redhat.com.*\n.*403 Forbidden.*'
because: Probably temporary, EXD-12345 to be fixed in early 2027
```

Or more likely in a shared top-level `waivers.fmf`:

```yaml
/dnf/Sanity/dnf-plugin-spacewalk-sanity:
     because: >-
         Probably temporary, ABC-12345 to be fixed in early 2027.
     waiver: /dnf/Sanity/dnf-plugin-spacewalk-sanity
     subresult: Install-a-pkg-with-GPG-verification
     grep: 'Connecting to some-hostname.redhat.com.*\n.*403 Forbidden.*'

/broken-upstream:
     because: >-
         Company XYZ has taken over upstream and merged a huge patch
         that breaks the upstream unit tests on RHEL/Fedora.
         See discussion in RHEL-123456.
     waiver:
       - /Sanity/upstream-suite
       - /Sanity/unit-tests/
     adjust:
         waiver+:
           - /Sanity/old-upstream
         when: distro < rhel-10

/RHEL-567890:
     waiver: /selinux-policy/.+/real-scenario-standalone-service
     when: arch != x86_64 and distro < rhel-9.9
```

Waivers would be discovered and `adjust`-ed just like any other fmf metadata.

## New test status: `waived`

During a test run, tmt could post-process test results and if a test name matches a waiver expression, change its status to `waived` - probably better than reusing `warn` or `info`.

## Inspired by existing `story` type?

* Stories have optional `title` / `description`, maybe `description` is better than `because` ?
* Re-using `link` ?
  * Currently: `implemented-by` / `documented-by` / `verified-by`
  * To-be-added? : `blocked-by` - what would cause the waiver to be removed?

## AI friendly

* AI can be used to identify a test failure and propose an automated waiver, proving via before / after that it matches.
* Human can review the reasoning and proposed waiver.
* From then on, the **automated deterministic waiver does the real work**.

## We were there already with Nitrate

* Nothing here is really revolutionary, we were here before.
* Years ago, we chose git and fmf metadata as the engineer-controlled reliable decentralized storage, placing test metadata next to test data.
* We did the same thing with user stories.
* This is just extending the concept to test failures and their classification.

## Why not [`xfail`](https://tmt.readthedocs.io/en/stable/spec/tests.html#result)

* Waivers should be centralized and easy to maintain
  * Test metadata is often scattered across many files and virtual test variants
* Waivers could match dynamically-reported subresults
* Waivers could inspect and grep logs
* One waiver can match many tests / results

## This is just an idea

* Feel free to modify / take / get inspired by whatever you see, and ignore what you don't like.

## Inspiration

* We [already use a variant of this](https://github.com/RHSecurityCompliance/contest/tree/main/conf/waivers), but it's test-suite-managed, not fmf-native, and uses a [custom micro-language](https://github.com/RHSecurityCompliance/contest/blob/main/docs/WAIVERS.md). Despite this, it has been invaluable in navigating dozens of infra/product bugs over the last 3-4 years and we can't live without it.

**Comment by comps** [comment]
Regarding multiple repositories/components - I think this works pretty seamlessly for both

1. separate per-component repositories with their own waiver files/nodes
2. centralized management in one repo

Nr. 1 works because `waiver` is a fmf/tmt style test expression using `re.search`, so `/Sanity/some-test` matches nicely within the repository itself, and also when run from a central "aggregator" plan with multiple `url`-based `discover` sections, because `re.search()` find `/Sanity/some-test` even when the test name has a prefix like `/libdnf/Sanity/some-test`.

And because waivers are fmf nodes, they would be seamlessly discovered via the same `url`-based `discover` as tests - I'm pretty sure `fmf` doesn't care about node "type" or test/plan/story/whatever differentiation.

Nr. 2 works because the waivers could be in the one "aggregator" repo used for execution, aggregating (again via multiple `url`-based `discover` sections) tests from multiple components, and locally defining just the plans and waivers.
